version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: reservations-postgres
    restart: always
    environment:
      POSTGRES_DB: reservations
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password123
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
